/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardVendorRouteImport } from './routes/_dashboard/vendor'
import { Route as DashboardUserRouteImport } from './routes/_dashboard/user'
import { Route as DashboardUnitRouteImport } from './routes/_dashboard/unit'
import { Route as DashboardTingkatRouteImport } from './routes/_dashboard/tingkat'
import { Route as DashboardTahunAjaranRouteImport } from './routes/_dashboard/tahun-ajaran'
import { Route as DashboardTagihanRouteImport } from './routes/_dashboard/tagihan'
import { Route as DashboardSppRouteImport } from './routes/_dashboard/spp'
import { Route as DashboardSiswaRouteImport } from './routes/_dashboard/siswa'
import { Route as DashboardRoleRouteImport } from './routes/_dashboard/role'
import { Route as DashboardPenggajianRouteImport } from './routes/_dashboard/penggajian'
import { Route as DashboardPengaturanRouteImport } from './routes/_dashboard/pengaturan'
import { Route as DashboardPegawaiRouteImport } from './routes/_dashboard/pegawai'
import { Route as DashboardLaporanKeuanganRouteImport } from './routes/_dashboard/laporan-keuangan'
import { Route as DashboardKurikulumRouteImport } from './routes/_dashboard/kurikulum'
import { Route as DashboardKeuanganRouteImport } from './routes/_dashboard/keuangan'
import { Route as DashboardKelasRouteImport } from './routes/_dashboard/kelas'
import { Route as DashboardKategoriRouteImport } from './routes/_dashboard/kategori'
import { Route as DashboardHutangPiutangRouteImport } from './routes/_dashboard/hutang-piutang'
import { Route as DashboardGeneralRouteImport } from './routes/_dashboard/general'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDanaRouteImport } from './routes/_dashboard/dana'
import { Route as DashboardCoaRouteImport } from './routes/_dashboard/coa'
import { Route as DashboardBosRouteImport } from './routes/_dashboard/bos'
import { Route as DashboardBeasiswaRouteImport } from './routes/_dashboard/beasiswa'
import { Route as DashboardBankRouteImport } from './routes/_dashboard/bank'
import { Route as DashboardAsetRouteImport } from './routes/_dashboard/aset'
import { Route as DashboardAnggaranRouteImport } from './routes/_dashboard/anggaran'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardTagihanIdRouteImport } from './routes/_dashboard/tagihan_.$id'
import { Route as DashboardSppIdRouteImport } from './routes/_dashboard/spp_.$id'
import { Route as DashboardSiswaIdRouteImport } from './routes/_dashboard/siswa_.$id'
import { Route as DashboardPenggajian_pegawaiIdRouteImport } from './routes/_dashboard/penggajian_pegawai_.$id'
import { Route as DashboardPegawaiIdRouteImport } from './routes/_dashboard/pegawai_.$id'
import { Route as DashboardKelasIdRouteImport } from './routes/_dashboard/kelas_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVendorRoute = DashboardVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnitRoute = DashboardUnitRouteImport.update({
  id: '/unit',
  path: '/unit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTingkatRoute = DashboardTingkatRouteImport.update({
  id: '/tingkat',
  path: '/tingkat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTahunAjaranRoute = DashboardTahunAjaranRouteImport.update({
  id: '/tahun-ajaran',
  path: '/tahun-ajaran',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTagihanRoute = DashboardTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSppRoute = DashboardSppRouteImport.update({
  id: '/spp',
  path: '/spp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSiswaRoute = DashboardSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPenggajianRoute = DashboardPenggajianRouteImport.update({
  id: '/penggajian',
  path: '/penggajian',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPengaturanRoute = DashboardPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPegawaiRoute = DashboardPegawaiRouteImport.update({
  id: '/pegawai',
  path: '/pegawai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLaporanKeuanganRoute =
  DashboardLaporanKeuanganRouteImport.update({
    id: '/laporan-keuangan',
    path: '/laporan-keuangan',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardKurikulumRoute = DashboardKurikulumRouteImport.update({
  id: '/kurikulum',
  path: '/kurikulum',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeuanganRoute = DashboardKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKelasRoute = DashboardKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKategoriRoute = DashboardKategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHutangPiutangRoute = DashboardHutangPiutangRouteImport.update({
  id: '/hutang-piutang',
  path: '/hutang-piutang',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGeneralRoute = DashboardGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDanaRoute = DashboardDanaRouteImport.update({
  id: '/dana',
  path: '/dana',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoaRoute = DashboardCoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBosRoute = DashboardBosRouteImport.update({
  id: '/bos',
  path: '/bos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBeasiswaRoute = DashboardBeasiswaRouteImport.update({
  id: '/beasiswa',
  path: '/beasiswa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBankRoute = DashboardBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAsetRoute = DashboardAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnggaranRoute = DashboardAnggaranRouteImport.update({
  id: '/anggaran',
  path: '/anggaran',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTagihanIdRoute = DashboardTagihanIdRouteImport.update({
  id: '/tagihan_/$id',
  path: '/tagihan/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSppIdRoute = DashboardSppIdRouteImport.update({
  id: '/spp_/$id',
  path: '/spp/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSiswaIdRoute = DashboardSiswaIdRouteImport.update({
  id: '/siswa_/$id',
  path: '/siswa/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPenggajian_pegawaiIdRoute =
  DashboardPenggajian_pegawaiIdRouteImport.update({
    id: '/penggajian_pegawai_/$id',
    path: '/penggajian_pegawai/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPegawaiIdRoute = DashboardPegawaiIdRouteImport.update({
  id: '/pegawai_/$id',
  path: '/pegawai/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKelasIdRoute = DashboardKelasIdRouteImport.update({
  id: '/kelas_/$id',
  path: '/kelas/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anggaran': typeof DashboardAnggaranRoute
  '/aset': typeof DashboardAsetRoute
  '/bank': typeof DashboardBankRoute
  '/beasiswa': typeof DashboardBeasiswaRoute
  '/bos': typeof DashboardBosRoute
  '/coa': typeof DashboardCoaRoute
  '/dana': typeof DashboardDanaRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/general': typeof DashboardGeneralRoute
  '/hutang-piutang': typeof DashboardHutangPiutangRoute
  '/kategori': typeof DashboardKategoriRoute
  '/kelas': typeof DashboardKelasRoute
  '/keuangan': typeof DashboardKeuanganRoute
  '/kurikulum': typeof DashboardKurikulumRoute
  '/laporan-keuangan': typeof DashboardLaporanKeuanganRoute
  '/pegawai': typeof DashboardPegawaiRoute
  '/pengaturan': typeof DashboardPengaturanRoute
  '/penggajian': typeof DashboardPenggajianRoute
  '/role': typeof DashboardRoleRoute
  '/siswa': typeof DashboardSiswaRoute
  '/spp': typeof DashboardSppRoute
  '/tagihan': typeof DashboardTagihanRoute
  '/tahun-ajaran': typeof DashboardTahunAjaranRoute
  '/tingkat': typeof DashboardTingkatRoute
  '/unit': typeof DashboardUnitRoute
  '/user': typeof DashboardUserRoute
  '/vendor': typeof DashboardVendorRoute
  '/kelas/$id': typeof DashboardKelasIdRoute
  '/pegawai/$id': typeof DashboardPegawaiIdRoute
  '/penggajian_pegawai/$id': typeof DashboardPenggajian_pegawaiIdRoute
  '/siswa/$id': typeof DashboardSiswaIdRoute
  '/spp/$id': typeof DashboardSppIdRoute
  '/tagihan/$id': typeof DashboardTagihanIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anggaran': typeof DashboardAnggaranRoute
  '/aset': typeof DashboardAsetRoute
  '/bank': typeof DashboardBankRoute
  '/beasiswa': typeof DashboardBeasiswaRoute
  '/bos': typeof DashboardBosRoute
  '/coa': typeof DashboardCoaRoute
  '/dana': typeof DashboardDanaRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/general': typeof DashboardGeneralRoute
  '/hutang-piutang': typeof DashboardHutangPiutangRoute
  '/kategori': typeof DashboardKategoriRoute
  '/kelas': typeof DashboardKelasRoute
  '/keuangan': typeof DashboardKeuanganRoute
  '/kurikulum': typeof DashboardKurikulumRoute
  '/laporan-keuangan': typeof DashboardLaporanKeuanganRoute
  '/pegawai': typeof DashboardPegawaiRoute
  '/pengaturan': typeof DashboardPengaturanRoute
  '/penggajian': typeof DashboardPenggajianRoute
  '/role': typeof DashboardRoleRoute
  '/siswa': typeof DashboardSiswaRoute
  '/spp': typeof DashboardSppRoute
  '/tagihan': typeof DashboardTagihanRoute
  '/tahun-ajaran': typeof DashboardTahunAjaranRoute
  '/tingkat': typeof DashboardTingkatRoute
  '/unit': typeof DashboardUnitRoute
  '/user': typeof DashboardUserRoute
  '/vendor': typeof DashboardVendorRoute
  '/kelas/$id': typeof DashboardKelasIdRoute
  '/pegawai/$id': typeof DashboardPegawaiIdRoute
  '/penggajian_pegawai/$id': typeof DashboardPenggajian_pegawaiIdRoute
  '/siswa/$id': typeof DashboardSiswaIdRoute
  '/spp/$id': typeof DashboardSppIdRoute
  '/tagihan/$id': typeof DashboardTagihanIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/anggaran': typeof DashboardAnggaranRoute
  '/_dashboard/aset': typeof DashboardAsetRoute
  '/_dashboard/bank': typeof DashboardBankRoute
  '/_dashboard/beasiswa': typeof DashboardBeasiswaRoute
  '/_dashboard/bos': typeof DashboardBosRoute
  '/_dashboard/coa': typeof DashboardCoaRoute
  '/_dashboard/dana': typeof DashboardDanaRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/general': typeof DashboardGeneralRoute
  '/_dashboard/hutang-piutang': typeof DashboardHutangPiutangRoute
  '/_dashboard/kategori': typeof DashboardKategoriRoute
  '/_dashboard/kelas': typeof DashboardKelasRoute
  '/_dashboard/keuangan': typeof DashboardKeuanganRoute
  '/_dashboard/kurikulum': typeof DashboardKurikulumRoute
  '/_dashboard/laporan-keuangan': typeof DashboardLaporanKeuanganRoute
  '/_dashboard/pegawai': typeof DashboardPegawaiRoute
  '/_dashboard/pengaturan': typeof DashboardPengaturanRoute
  '/_dashboard/penggajian': typeof DashboardPenggajianRoute
  '/_dashboard/role': typeof DashboardRoleRoute
  '/_dashboard/siswa': typeof DashboardSiswaRoute
  '/_dashboard/spp': typeof DashboardSppRoute
  '/_dashboard/tagihan': typeof DashboardTagihanRoute
  '/_dashboard/tahun-ajaran': typeof DashboardTahunAjaranRoute
  '/_dashboard/tingkat': typeof DashboardTingkatRoute
  '/_dashboard/unit': typeof DashboardUnitRoute
  '/_dashboard/user': typeof DashboardUserRoute
  '/_dashboard/vendor': typeof DashboardVendorRoute
  '/_dashboard/kelas_/$id': typeof DashboardKelasIdRoute
  '/_dashboard/pegawai_/$id': typeof DashboardPegawaiIdRoute
  '/_dashboard/penggajian_pegawai_/$id': typeof DashboardPenggajian_pegawaiIdRoute
  '/_dashboard/siswa_/$id': typeof DashboardSiswaIdRoute
  '/_dashboard/spp_/$id': typeof DashboardSppIdRoute
  '/_dashboard/tagihan_/$id': typeof DashboardTagihanIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anggaran'
    | '/aset'
    | '/bank'
    | '/beasiswa'
    | '/bos'
    | '/coa'
    | '/dana'
    | '/dashboard'
    | '/general'
    | '/hutang-piutang'
    | '/kategori'
    | '/kelas'
    | '/keuangan'
    | '/kurikulum'
    | '/laporan-keuangan'
    | '/pegawai'
    | '/pengaturan'
    | '/penggajian'
    | '/role'
    | '/siswa'
    | '/spp'
    | '/tagihan'
    | '/tahun-ajaran'
    | '/tingkat'
    | '/unit'
    | '/user'
    | '/vendor'
    | '/kelas/$id'
    | '/pegawai/$id'
    | '/penggajian_pegawai/$id'
    | '/siswa/$id'
    | '/spp/$id'
    | '/tagihan/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/anggaran'
    | '/aset'
    | '/bank'
    | '/beasiswa'
    | '/bos'
    | '/coa'
    | '/dana'
    | '/dashboard'
    | '/general'
    | '/hutang-piutang'
    | '/kategori'
    | '/kelas'
    | '/keuangan'
    | '/kurikulum'
    | '/laporan-keuangan'
    | '/pegawai'
    | '/pengaturan'
    | '/penggajian'
    | '/role'
    | '/siswa'
    | '/spp'
    | '/tagihan'
    | '/tahun-ajaran'
    | '/tingkat'
    | '/unit'
    | '/user'
    | '/vendor'
    | '/kelas/$id'
    | '/pegawai/$id'
    | '/penggajian_pegawai/$id'
    | '/siswa/$id'
    | '/spp/$id'
    | '/tagihan/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/anggaran'
    | '/_dashboard/aset'
    | '/_dashboard/bank'
    | '/_dashboard/beasiswa'
    | '/_dashboard/bos'
    | '/_dashboard/coa'
    | '/_dashboard/dana'
    | '/_dashboard/dashboard'
    | '/_dashboard/general'
    | '/_dashboard/hutang-piutang'
    | '/_dashboard/kategori'
    | '/_dashboard/kelas'
    | '/_dashboard/keuangan'
    | '/_dashboard/kurikulum'
    | '/_dashboard/laporan-keuangan'
    | '/_dashboard/pegawai'
    | '/_dashboard/pengaturan'
    | '/_dashboard/penggajian'
    | '/_dashboard/role'
    | '/_dashboard/siswa'
    | '/_dashboard/spp'
    | '/_dashboard/tagihan'
    | '/_dashboard/tahun-ajaran'
    | '/_dashboard/tingkat'
    | '/_dashboard/unit'
    | '/_dashboard/user'
    | '/_dashboard/vendor'
    | '/_dashboard/kelas_/$id'
    | '/_dashboard/pegawai_/$id'
    | '/_dashboard/penggajian_pegawai_/$id'
    | '/_dashboard/siswa_/$id'
    | '/_dashboard/spp_/$id'
    | '/_dashboard/tagihan_/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/vendor': {
      id: '/_dashboard/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof DashboardVendorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/user': {
      id: '/_dashboard/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/unit': {
      id: '/_dashboard/unit'
      path: '/unit'
      fullPath: '/unit'
      preLoaderRoute: typeof DashboardUnitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tingkat': {
      id: '/_dashboard/tingkat'
      path: '/tingkat'
      fullPath: '/tingkat'
      preLoaderRoute: typeof DashboardTingkatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tahun-ajaran': {
      id: '/_dashboard/tahun-ajaran'
      path: '/tahun-ajaran'
      fullPath: '/tahun-ajaran'
      preLoaderRoute: typeof DashboardTahunAjaranRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tagihan': {
      id: '/_dashboard/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof DashboardTagihanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/spp': {
      id: '/_dashboard/spp'
      path: '/spp'
      fullPath: '/spp'
      preLoaderRoute: typeof DashboardSppRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/siswa': {
      id: '/_dashboard/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof DashboardSiswaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/role': {
      id: '/_dashboard/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/penggajian': {
      id: '/_dashboard/penggajian'
      path: '/penggajian'
      fullPath: '/penggajian'
      preLoaderRoute: typeof DashboardPenggajianRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pengaturan': {
      id: '/_dashboard/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof DashboardPengaturanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pegawai': {
      id: '/_dashboard/pegawai'
      path: '/pegawai'
      fullPath: '/pegawai'
      preLoaderRoute: typeof DashboardPegawaiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/laporan-keuangan': {
      id: '/_dashboard/laporan-keuangan'
      path: '/laporan-keuangan'
      fullPath: '/laporan-keuangan'
      preLoaderRoute: typeof DashboardLaporanKeuanganRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/kurikulum': {
      id: '/_dashboard/kurikulum'
      path: '/kurikulum'
      fullPath: '/kurikulum'
      preLoaderRoute: typeof DashboardKurikulumRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/keuangan': {
      id: '/_dashboard/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof DashboardKeuanganRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/kelas': {
      id: '/_dashboard/kelas'
      path: '/kelas'
      fullPath: '/kelas'
      preLoaderRoute: typeof DashboardKelasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/kategori': {
      id: '/_dashboard/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof DashboardKategoriRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/hutang-piutang': {
      id: '/_dashboard/hutang-piutang'
      path: '/hutang-piutang'
      fullPath: '/hutang-piutang'
      preLoaderRoute: typeof DashboardHutangPiutangRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/general': {
      id: '/_dashboard/general'
      path: '/general'
      fullPath: '/general'
      preLoaderRoute: typeof DashboardGeneralRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dana': {
      id: '/_dashboard/dana'
      path: '/dana'
      fullPath: '/dana'
      preLoaderRoute: typeof DashboardDanaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/coa': {
      id: '/_dashboard/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof DashboardCoaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bos': {
      id: '/_dashboard/bos'
      path: '/bos'
      fullPath: '/bos'
      preLoaderRoute: typeof DashboardBosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/beasiswa': {
      id: '/_dashboard/beasiswa'
      path: '/beasiswa'
      fullPath: '/beasiswa'
      preLoaderRoute: typeof DashboardBeasiswaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bank': {
      id: '/_dashboard/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof DashboardBankRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/aset': {
      id: '/_dashboard/aset'
      path: '/aset'
      fullPath: '/aset'
      preLoaderRoute: typeof DashboardAsetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/anggaran': {
      id: '/_dashboard/anggaran'
      path: '/anggaran'
      fullPath: '/anggaran'
      preLoaderRoute: typeof DashboardAnggaranRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/tagihan_/$id': {
      id: '/_dashboard/tagihan_/$id'
      path: '/tagihan/$id'
      fullPath: '/tagihan/$id'
      preLoaderRoute: typeof DashboardTagihanIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/spp_/$id': {
      id: '/_dashboard/spp_/$id'
      path: '/spp/$id'
      fullPath: '/spp/$id'
      preLoaderRoute: typeof DashboardSppIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/siswa_/$id': {
      id: '/_dashboard/siswa_/$id'
      path: '/siswa/$id'
      fullPath: '/siswa/$id'
      preLoaderRoute: typeof DashboardSiswaIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/penggajian_pegawai_/$id': {
      id: '/_dashboard/penggajian_pegawai_/$id'
      path: '/penggajian_pegawai/$id'
      fullPath: '/penggajian_pegawai/$id'
      preLoaderRoute: typeof DashboardPenggajian_pegawaiIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pegawai_/$id': {
      id: '/_dashboard/pegawai_/$id'
      path: '/pegawai/$id'
      fullPath: '/pegawai/$id'
      preLoaderRoute: typeof DashboardPegawaiIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/kelas_/$id': {
      id: '/_dashboard/kelas_/$id'
      path: '/kelas/$id'
      fullPath: '/kelas/$id'
      preLoaderRoute: typeof DashboardKelasIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnggaranRoute: typeof DashboardAnggaranRoute
  DashboardAsetRoute: typeof DashboardAsetRoute
  DashboardBankRoute: typeof DashboardBankRoute
  DashboardBeasiswaRoute: typeof DashboardBeasiswaRoute
  DashboardBosRoute: typeof DashboardBosRoute
  DashboardCoaRoute: typeof DashboardCoaRoute
  DashboardDanaRoute: typeof DashboardDanaRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardGeneralRoute: typeof DashboardGeneralRoute
  DashboardHutangPiutangRoute: typeof DashboardHutangPiutangRoute
  DashboardKategoriRoute: typeof DashboardKategoriRoute
  DashboardKelasRoute: typeof DashboardKelasRoute
  DashboardKeuanganRoute: typeof DashboardKeuanganRoute
  DashboardKurikulumRoute: typeof DashboardKurikulumRoute
  DashboardLaporanKeuanganRoute: typeof DashboardLaporanKeuanganRoute
  DashboardPegawaiRoute: typeof DashboardPegawaiRoute
  DashboardPengaturanRoute: typeof DashboardPengaturanRoute
  DashboardPenggajianRoute: typeof DashboardPenggajianRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
  DashboardSiswaRoute: typeof DashboardSiswaRoute
  DashboardSppRoute: typeof DashboardSppRoute
  DashboardTagihanRoute: typeof DashboardTagihanRoute
  DashboardTahunAjaranRoute: typeof DashboardTahunAjaranRoute
  DashboardTingkatRoute: typeof DashboardTingkatRoute
  DashboardUnitRoute: typeof DashboardUnitRoute
  DashboardUserRoute: typeof DashboardUserRoute
  DashboardVendorRoute: typeof DashboardVendorRoute
  DashboardKelasIdRoute: typeof DashboardKelasIdRoute
  DashboardPegawaiIdRoute: typeof DashboardPegawaiIdRoute
  DashboardPenggajian_pegawaiIdRoute: typeof DashboardPenggajian_pegawaiIdRoute
  DashboardSiswaIdRoute: typeof DashboardSiswaIdRoute
  DashboardSppIdRoute: typeof DashboardSppIdRoute
  DashboardTagihanIdRoute: typeof DashboardTagihanIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnggaranRoute: DashboardAnggaranRoute,
  DashboardAsetRoute: DashboardAsetRoute,
  DashboardBankRoute: DashboardBankRoute,
  DashboardBeasiswaRoute: DashboardBeasiswaRoute,
  DashboardBosRoute: DashboardBosRoute,
  DashboardCoaRoute: DashboardCoaRoute,
  DashboardDanaRoute: DashboardDanaRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardGeneralRoute: DashboardGeneralRoute,
  DashboardHutangPiutangRoute: DashboardHutangPiutangRoute,
  DashboardKategoriRoute: DashboardKategoriRoute,
  DashboardKelasRoute: DashboardKelasRoute,
  DashboardKeuanganRoute: DashboardKeuanganRoute,
  DashboardKurikulumRoute: DashboardKurikulumRoute,
  DashboardLaporanKeuanganRoute: DashboardLaporanKeuanganRoute,
  DashboardPegawaiRoute: DashboardPegawaiRoute,
  DashboardPengaturanRoute: DashboardPengaturanRoute,
  DashboardPenggajianRoute: DashboardPenggajianRoute,
  DashboardRoleRoute: DashboardRoleRoute,
  DashboardSiswaRoute: DashboardSiswaRoute,
  DashboardSppRoute: DashboardSppRoute,
  DashboardTagihanRoute: DashboardTagihanRoute,
  DashboardTahunAjaranRoute: DashboardTahunAjaranRoute,
  DashboardTingkatRoute: DashboardTingkatRoute,
  DashboardUnitRoute: DashboardUnitRoute,
  DashboardUserRoute: DashboardUserRoute,
  DashboardVendorRoute: DashboardVendorRoute,
  DashboardKelasIdRoute: DashboardKelasIdRoute,
  DashboardPegawaiIdRoute: DashboardPegawaiIdRoute,
  DashboardPenggajian_pegawaiIdRoute: DashboardPenggajian_pegawaiIdRoute,
  DashboardSiswaIdRoute: DashboardSiswaIdRoute,
  DashboardSppIdRoute: DashboardSppIdRoute,
  DashboardTagihanIdRoute: DashboardTagihanIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
